### PR TITLE
Add action_name_prefix and use_fake_user

### PR DESCRIPTION
**Pull request by cuddlyogre**
Add an option to specify an action name prefix and to mark whether the sent action should have a fake user. There is a companion addition to cc_blender_tools. The rationale is that it makes it easier to organize and preserve poses and motions sent to Blender.

### CODE REVIEW

**Comment by soupday** [comment]
Ok, I'll take it.

There may be problems with Retargeting if later Rigifying as I use the first part of the name to identify the source rig... however I am going to move away from putting the identifiers in the name, as this is too easy to break, and put them in custom properties instead, so this won't be a problem much longer.

**Comment by cuddlyogre** [comment]
Fantastic! This feature saved me probably a couple hours of work yesterday and I'm glad it can help other people, too.
The code for this plugin is very clean and intuitive. It was a treat to work with.

**Comment by cuddlyogre** [comment]
Is there a way to get the name of the pose/motion when you apply it to the character? If so, having that be the default name or prefix for poses and motions would be incredibly helpful.

I've looked through https://wiki.reallusion.com/IC_Python_API:RL_Python_Modules#Animation but I'm not finding anything.

**Comment by soupday** [comment]
Clips do have names but it is not exposed in the API.

**Pull request merged**
